name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run_tests:
    name: ${{ matrix.pixi-environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pixi-environment:
          - py312
          - py311
          - py310
          - py39
          - py38
    steps:
        - uses: actions/checkout@v4
        - uses: prefix-dev/setup-pixi@v0.5.1
          with:
            pixi-version: "latest"
            environments: ${{ matrix.pixi-environment }}
        - name: run tests
          run: |
           pixi run --environment ${{ matrix.pixi-environment }} tests
